### ISSUE TITLE
GraphiQl wont work after installing this plugin

### ISSUE THREAD

**Issue by jenishshrestha** [DalkMania/wp-graphql-cpt#1]
graphiql doesnot show any schema in explorer after installing this plugin.

**Comment by DalkMania** [comment]
Thanks @jenishshrestha . I'll check it out, and see if I can fix it over the weekend possibly.

**Comment by DalkMania** [comment]
Ok @jenishshrestha . I think that should fix it. Thanks for letting me know 👍
