### ISSUE TITLE
It doesn't work

### ISSUE THREAD

**Issue by elcijcampeador** [DalkMania/wp-graphql-cpt#2]
Sorry don't know enough to give more data than this:
Once I activate this plugin, WP GraphQL stops working. No errors. No messages. No warnings.
Document explorer, explorer all blank. No schema found for anything.
When I disable the plugin, everything works just fine again.

debug for wordpress and graphql is on and I still get no messages.

**Comment by DalkMania** [comment]
Hey @elcijcampeador 

Which version of WP-GraphQL are you using?

**Comment by elcijcampeador** [comment]
WP GraphQL: Version 1.2.6
WP GraphQL for Advanced Custom Fields: Version 0.4.1
WP GraphQL JWT Authentication: Version 0.4.0
WP GraphQL Woocommerce: Version 0.8.1

Thanks for responding!
Just noticed something while trying to access the endpoint directly:

`Fatal error: Uncaught GraphQL\Error\InvariantViolation: The acf-field-group-category taxonomy cannot declare the same value for "graphql_single_name" and "graphql_plural_name". in /var/www/wpgqldev.local/public_html/wp-content/plugins/wp-graphql/src/Registry/TypeRegistry.php:457 Stack trace: #0 /var/www/wpgqldev.local/public_html/wp-includes/class-wp-hook.php(292): WPGraphQL\Registry\TypeRegistry->init_type_registry() #1 /var/www/wpgqldev.local/public_html/wp-includes/class-wp-hook.php(316): WP_Hook->apply_filters() #2 /var/www/wpgqldev.local/public_html/wp-includes/plugin.php(484): WP_Hook->do_action() #3 /var/www/wpgqldev.local/public_html/wp-content/plugins/wp-graphql/src/Registry/TypeRegistry.php(197): do_action() #4 /var/www/wpgqldev.local/public_html/wp-content/plugins/wp-graphql/src/Registry/SchemaRegistry.php(37): WPGraphQL\Registry\TypeRegistry->init() #5 /var/www/wpgqldev.local/public_html/wp-content/plugins/wp-graphql/src/WPGraphQL.php(576): WPGraphQL\Registry\Sc in /var/www/wpgqldev.local/public_html/wp-content/plugins/wp-graphql/src/Registry/TypeRegistry.php on line 457`

It seems it the acf plugin and yours don't play nice...

Edit: happens even when the graphql acf plugin is disabled

**Comment by DalkMania** [comment]
Ok thanks for the information. I'll see what I can do. Error messages help a lot 👍  @elcijcampeador

**Comment by DalkMania** [comment]
Ok @elcijcampeador ... 

I think that will fix it. Thanks for letting me know about this.
