### ISSUE TITLE
Custom taxonomies with special characters

### ISSUE THREAD

**Issue by arber1** [DalkMania/wp-graphql-cpt#3]
I have custom taxonomies with special characters included and wpgraphql cpt doesn't know this pattern, how can i fix it?

**Comment by DalkMania** [comment]
Hey @arber1 ... Can you please give me an example? Or an error message. So I can look into this.

**Comment by arber1** [comment]
Hey @DalkMania, thats what i get on console and IDE stay loading.
![image](https://user-images.githubusercontent.com/5586260/167247345-68501abe-d9d4-45eb-8f2c-cdf43a3e504b.png)

**Comment by DalkMania** [comment]
Hey @arber1 .. I made an update. Please test it out and let me know, if it works for you.

**Comment by arber1** [comment]
Helyy @DalkMania Now im getting this 
![image](https://user-images.githubusercontent.com/5586260/167290813-d02e8e4a-db9c-4ada-a1e6-dccd7848e17c.png)


UPDATE!
Also prevent user login.
Error log:
[08-May-2022 15:00:17 UTC] Connection refused
[08-May-2022 15:00:17 UTC] PHP Warning:  Undefined array key "singular_name" in .../wp-content/plugins/wp-graphql-cpt-master/wp-graphql-cpt.php on line 81

**Comment by DalkMania** [comment]
Ok @arber1 .. Thanks for the update. I'll look again :)

**Comment by DalkMania** [comment]
Hey @arber1 .. It looks like you are missing the `singular_name` key in the taxonomy labels array. More information here: https://developer.wordpress.org/reference/functions/get_taxonomy_labels/. 

Do you have the opportunity to add that? It should work after.

**Comment by arber1** [comment]
Yeah i can do it by myself. Thanks

**Comment by DalkMania** [comment]
Great @arber1 . Thanks for reporting this issue.

**Comment by arber1** [comment]
Thank you too!
