### ISSUE TITLE
Custom taxonomies do not show up in where argument for custom post type query

### ISSUE THREAD

**Issue by H-Nguyenx** [DalkMania/wp-graphql-cpt#5]
Hi, I've install your plugin and it works for product type. Thanks.

I have a custom post type - Hospital with a custom taxonomy attach to it - Hospital Category.
I want to query hospitals in specific hospital category but in the where argument of hospitals, I do not see the taxonomyFilter.

Can you help me?

![image](https://user-images.githubusercontent.com/33373945/200255687-6463f725-747d-4871-8b19-68c11b44f397.png)

**Comment by DalkMania** [comment]
Maybe something like this @H-Nguyenx 

```
query NewQuery {
  hospitalCategories(where: {slug: "whatever-slug"}) {
    nodes {
      slug
      hospitals {
        nodes {
          slug
        }
      }
    }
  }
}
```

I think that should work
